### PR TITLE
Make use of ember-frost-core z-index variable

### PR DESCRIPTION
**Pull request by EWhite613**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* Make use of ember-frost-core z-index variable

### CODE REVIEW

**Comment by rox163** [comment]
:+1:

**Comment by rox163** [comment]
wait isnt there a 9000 index somewhere in date-picker as well?

**Comment by EWhite613** [comment]
@rox163 yep https://github.com/ciena-frost/ember-frost-date-picker/blob/91eedc5f68b3901a3e3435731ed569eb959f4a61/addon/styles/_clockpicker.scss#L3

**Comment by rox163** [comment]
:+1:

**Comment by sglanzer** [comment]
This is why we try to centralize the z-index https://github.com/ciena-frost/ember-frost-core/blob/master/addon/styles/_z-index.scss

Can you cross reference this against common z-index values to see if one will work or needs to be added?

**Comment by sglanzer** [comment]
Obviously it looks like we'll need to decide if we're going to flip modal and notification z-indices

**Comment by EWhite613** [comment]
So after the https://github.com/ciena-frost/ember-frost-core/pull/458 PR is dealt with I'll make changes to have notifier make use of core's z-index variable

**Comment by sglanzer** [comment]
@EWhite613 Can you up the semver dependency on core to the version that includes the latest z-index?  We want to use the variable, but we should move up to enforce the right ones :)

**Comment by sglanzer** [comment]
Approved

**Pull request merged**
