### PR TITLE
Fix Issue #39

### PR DESCRIPTION
**Pull request by job13er**
https://github.com/ciena-frost/ember-frost-notifier/issues/39

### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# Screenshots

## Before
screen shot 2017-05-22 at 1 04 44 pm

## After
screen shot 2017-05-22 at 1 05 11 pm

# CHANGELOG
* **Fixed** display of long, unbroken strings (resolves [#39](https://github.com/ciena-frost/ember-frost-notifier/issues/39))

### CODE REVIEW

**Comment by sglanzer** [comment]
Approved - probably still worth keeping some remnant of #39 around to handle the 
image ugliness

**Comment by job13er** [comment]
I've never had a use case for the open details thing, or actually even seen it configured properly, so I wasn't worried about it.

**Comment by sglanzer** [comment]
Yeah, me either ;)

**Comment by job13er** [comment]
Approved

**Comment by gknoy** [comment]
Awesome.

**Pull request merged**
